name: ecg
dependencies:
- appnope=0.1.0=py35_0
- backports=1.0=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.9=py35_0
- entrypoints=0.2=py35_1
- freetype=2.5.5=0
- get_terminal_size=1.0.0=py35_0
- h5py=2.6.0=np111py35_2
- hdf5=1.8.17=1
- ipykernel=4.3.1=py35_0
- ipython=4.2.0=py35_0
- ipython-notebook=4.0.4=py35_0
- ipython_genutils=0.1.0=py35_0
- jinja2=2.8=py35_0
- jsonschema=2.4.0=py35_0
- jupyter_client=4.2.2=py35_0
- jupyter_core=4.1.0=py35_0
- libpng=1.6.17=0
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np111py35_0
- mistune=0.7.2=py35_1
- mkl=11.3.3=0
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.2.0=py35_0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pandas=0.18.0=np111py35_0
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.5=py35_0
- pip=8.1.2=py35_0
- psycopg2=2.6.1=py35_1
- ptyprocess=0.5=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.1=py35_0
- pyqt=4.11.4=py35_1
- python=3.5.2=0
- python-dateutil=2.5.2=py35_0
- pytz=2016.3=py35_0
- pyzmq=15.2.0=py35_0
- qt=4.8.7=1
- readline=6.2=2
- scikit-learn=0.18=np111py35_0
- scipy=0.18.1=np111py35_0
- seaborn=0.7.0=py35_0
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.2.1=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - beautifulsoup4==4.5.1
  - biosppy==0.3.0
  - boto3==1.4.0
  - botocore==1.4.48
  - cffi==1.8.2
  - cloudpickle==0.2.1
  - cryptography==1.5
  - cython==0.25.1
  - db.py==0.4.4
  - devicesavvy==1.0.3
  - dill==0.2.5
  - docutils==0.12
  - funcy==1.7.1
  - gspread==0.4.1
  - httplib2==0.9.2
  - idna==2.1
  - imbalanced-learn==0.1.8
  - ipython-genutils==0.1.0
  - jmespath==0.9.0
  - jupyter-client==4.4.0
  - jupyter-core==4.2.0
  - keras==1.0.7
  - mechanize==0.2.5
  - memoized-property==1.0.2
  - oauth2client==3.0.0
  - patsy==0.4.1
  - prettytable==0.7.2
  - prompt-toolkit==1.0.9
  - pyasn1==0.1.9
  - pyasn1-modules==0.0.8
  - pybars3==0.9.1
  - pycparser==2.14
  - pymeta3==0.5.1
  - pymlconf==0.3.20
  - pyopenssl==16.1.0
  - pysavvy==1.0.2
  - pysensorbase==1.0.4
  - pyyaml==3.11
  - requests==2.11.1
  - rsa==3.4.2
  - s3transfer==0.1.2
  - savvyppg==0.1
  - sensorlib==1.0.14
  - sklearn==0.0
  - sqlalchemy==1.0.14
  - statsmodels==0.6.1
  - theano==0.8.2
  - toolz==0.8.0
  - wfdb==0.1.2
  - wcwidth==0.1.7
